name: Node.js CI & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  deploy:
    name: Deploy to 128.199.197.230
    needs: build
    runs-on: ubuntu-latest
    # Chỉ chạy khi push main hoặc PR đã merge vào main
    if: >
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' &&
       github.event.action == 'closed' &&
       github.event.pull_request.merged == true &&
       github.event.pull_request.base.ref == 'main')
    steps:
      - name: Checkout (for context)
        uses: actions/checkout@v4

      - name: SSH Deploy (git checkout/pull + pm2 restart)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            cd "${WORKDIR:-/var/www/techleet}"

            # Bảo vệ nếu repo bẩn
            git reset --hard

            # Đảm bảo đang ở nhánh main và lấy code mới nhất
            git fetch --all --prune
            git checkout main
            git pull --rebase --stat

           
            pnpm run build

            # Restart PM2 app
            pm2 describe "${PM2_NAME:-techleet}" >/dev/null 2>&1 || {
              echo "PM2 process not found, starting..."
              # Ví dụ nếu bạn dùng ecosystem file:
              # pm2 start ecosystem.config.js --only "${PM2_NAME:-techleet}"
              # hoặc start trực tiếp:
              # pm2 start dist/main.js --name "${PM2_NAME:-techleet}"
            }
            pm2 restart "${PM2_NAME:-techleet}"
            pm2 save
    environment:
      name: production
    concurrency:
      group: deploy-production
      cancel-in-progress: false
